In [1]:
import pandas as pd

**Прочитайте файл 2017_jun_final.csv за допомогою методу read_csv**

In [4]:
file_id = '1JMYqXipZpz9Y5-vyxvLEO2Y1sRBxqu-U'
url = f'https://drive.google.com/uc?id={file_id}'
data = pd.read_csv(url)
#print(data)

**Прочитайте отриману таблицю, використовуючи метод head**

In [5]:
data.head()

,N,Должность,Язык.программирования,Специализация,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,...,Еще.студент,Уровень.английского,Предметная.область,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Валюта,cls
0,1,Junior QA engineer,NaN,Manual QA,0.5,0.5,400,0,Харьков,до 10 человек,...,True,ниже среднего,"iOS,eCommerce",12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,QA
1,2,Junior QA engineer,NaN,Manual QA,меньше 3 месяцев,меньше 3 месяцев,430,130,Харьков,свыше 1000 человек,...,True,выше среднего,Веб-разработка,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN,QA
2,3,Software Engineer,C#/.NET,NaN,4,1,2500,800,Киев,до 1000 человек,...,False,средний,"Веб-разработка,Корпоративные системы",12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,NaN,DEV
3,4,Software Engineer,JavaScript,NaN,5,4,2000,400,Одесса,до 200 человек,...,False,ниже среднего,"Desktop Applications,Веб-разработка",12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,NaN,DEV
4,5,Senior Software Engineer,JavaScript,NaN,10 и более лет,0.5,4500,500,Другой,до 10 человек,...,False,средний,"Desktop Applications,Веб-разработка",12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,NaN,DEV

**Визначте розмір таблиці за допомогою методу shape**

In [7]:
data.shape

(8704, 25)

**Визначте типи всіх стовпців за допомогою dataframe.dtypes**

In [8]:
data.dtypes

N                                     int64
Должность                            object
Язык.программирования                object
Специализация                        object
Общий.опыт.работы                    object
Опыт.работы.на.текущем.месте         object
Зарплата.в.месяц                      int64
Изменение.зарплаты.за.12.месяцев      int64
Город                                object
Размер.компании                      object
Тип.компании                         object
Пол                                  object
Возраст                               int64
Образование                          object
Университет                          object
Еще.студент                            bool
Уровень.английского                  object
Предметная.область                   object
Дата.заполнения                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

**Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)**

In [20]:
data.isnull().sum()
data.columns
for i in data.columns:
    print(f"В колонці {i} частка пропусків складає {data[i].isnull().sum()/len(data[i])}")

В колонці N частка пропусків складає 0.0
В колонці Должность частка пропусків складає 0.0
В колонці Язык.программирования частка пропусків складає 0.4423253676470588
В колонці Специализация частка пропусків складає 0.8293887867647058
В колонці Общий.опыт.работы частка пропусків складає 0.0
В колонці Опыт.работы.на.текущем.месте частка пропусків складає 0.0
В колонці Зарплата.в.месяц частка пропусків складає 0.0
В колонці Изменение.зарплаты.за.12.месяцев частка пропусків складає 0.0
В колонці Город частка пропусків складає 0.0
В колонці Размер.компании частка пропусків складає 0.0
В колонці Тип.компании частка пропусків складає 0.0
В колонці Пол частка пропусків складає 0.0
В колонці Возраст частка пропусків складає 0.0
В колонці Образование частка пропусків складає 0.0
В колонці Университет частка пропусків складає 0.04113051470588235
В колонці Еще.студент частка пропусків складає 0.0
В колонці Уровень.английского частка пропусків складає 0.0
В колонці Предметная.область частка пропусків складає 0.025620404411764705
В колонці Дата.заполнения частка пропусків складає 0.0
В колонці User.Agent частка пропусків складає 0.0
В колонці exp частка пропусків складає 0.0
В колонці current_job_exp частка пропусків складає 0.0
В колонці salary частка пропусків складає 0.0
В колонці Валюта частка пропусків складає 0.9988511029411765
В колонці cls частка пропусків складає 0.18083639705882354

**Видаліть усі стовпці з пропусками, крім стовпця "Мова програмування", Знову порахуйте, яка частка пропусків міститься в кожній колонці і переконайтеся, що залишився тільки стовпець "Мова.програмування"**

In [32]:
new_data=data.copy()
drop_data = new_data.isna().any()
cols_ignore = ['Язык.программирования']
drop_data[cols_ignore] = False
new_data.drop(drop_data.index[drop_data], axis=1, inplace=True)
new_data.isnull().sum()

N                                      0
Должность                              0
Язык.программирования               3850
Общий.опыт.работы                      0
Опыт.работы.на.текущем.месте           0
Зарплата.в.месяц                       0
Изменение.зарплаты.за.12.месяцев       0
Город                                  0
Размер.компании                        0
Тип.компании                           0
Пол                                    0
Возраст                                0
Образование                            0
Еще.студент                            0
Уровень.английского                    0
Дата.заполнения                        0
User.Agent                             0
exp                                    0
current_job_exp                        0
salary                                 0
dtype: int64

**Видаліть усі рядки у вихідній таблиці за допомогою методу dropna; Визначте новий розмір таблиці за допомогою методу shape**

In [51]:
zero_data=new_data.dropna(inplace=True)
zero_data.shape

**Створіть нову таблицю python_data, в якій будуть тільки рядки зі спеціалістами, які вказали мову програмування Python; Визначте розмір таблиці python_data за допомогою методу shape**

In [55]:
python_data = pd.DataFrame(data.loc[data['Язык.программирования'] == 'Python'])
python_data

,N,Должность,Язык.программирования,Специализация,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,...,Еще.студент,Уровень.английского,Предметная.область,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Валюта,cls
12,13,Software Engineer,Python,NaN,1,меньше 3 месяцев,800,200,Киев,до 50 человек,...,False,ниже среднего,"Веб-разработка,Другое",12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.0,0.0,800,NaN,DEV
68,69,Software Engineer,Python,NaN,1.5,0.5,900,900,Киев,до 10 человек,...,True,выше среднего,Веб-разработка,12/06/2017 13:11:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.5,0.5,900,NaN,DEV
87,88,Junior Software Engineer,Python,NaN,0.5,0.5,600,0,Киев,до 10 человек,...,True,выше среднего,"Веб-разработка,eCommerce",12/06/2017 13:12:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.5,0.5,600,NaN,DEV
114,115,Junior Software Engineer,Python,NaN,1.5,0.5,685,250,Киев,до 1000 человек,...,False,средний,Другое,12/06/2017 13:14:52,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.5,0.5,685,NaN,DEV
143,144,Junior Software Engineer,Python,NaN,1,1,750,250,Киев,до 10 человек,...,True,выше среднего,Веб-разработка,12/06/2017 13:19:10,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,1.0,750,NaN,DEV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8546,8547,Software Engineer,Python,NaN,5,1,2000,800,Запорожье,до 50 человек,...,False,средний,Веб-разработка,10/07/2017 14:11:26,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,5.0,1.0,2000,NaN,DEV
8625,8626,Software Engineer,Python,NaN,4,1,1750,0,Киев,свыше 1000 человек,...,False,средний,Веб-разработка,11/07/2017 16:15:40,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,4.0,1.0,1750,NaN,DEV
8635,8636,Senior Software Engineer,Python,NaN,10 и более лет,меньше 3 месяцев,4000,1300,Удаленно,до 10 человек,...,False,выше среднего,Веб-разработка,11/07/2017 17:51:36,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,10.0,0.0,4000,NaN,DEV
8673,8674,Junior Software Engineer,Python,NaN,0.5,0.5,350,50,Киев,до 50 человек,...,False,средний,Веб-разработка,12/07/2017 09:37:16,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,0.5,0.5,350,NaN,DEV
8695,8696,Software Engineer,Python,NaN,1,0.5,1500,1000,Киев,до 10 человек,...,False,средний,"Финансы и банки,eCommerce",12/07/2017 14:39:21,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,1500,NaN,DEV

In [56]:
python_data.shape

(207, 25)

**Використовуючи метод groupby, виконайте групування за стовпчиком "Посада"**

In [64]:
position = python_data.groupby(['Должность'])

In [65]:
position.head()

,N,Должность,Язык.программирования,Специализация,Общий.опыт.работы,Опыт.работы.на.текущем.месте,Зарплата.в.месяц,Изменение.зарплаты.за.12.месяцев,Город,Размер.компании,...,Еще.студент,Уровень.английского,Предметная.область,Дата.заполнения,User.Agent,exp,current_job_exp,salary,Валюта,cls
12,13,Software Engineer,Python,NaN,1,меньше 3 месяцев,800,200,Киев,до 50 человек,...,False,ниже среднего,"Веб-разработка,Другое",12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.00,0.00,800,NaN,DEV
68,69,Software Engineer,Python,NaN,1.5,0.5,900,900,Киев,до 10 человек,...,True,выше среднего,Веб-разработка,12/06/2017 13:11:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.50,0.50,900,NaN,DEV
87,88,Junior Software Engineer,Python,NaN,0.5,0.5,600,0,Киев,до 10 человек,...,True,выше среднего,"Веб-разработка,eCommerce",12/06/2017 13:12:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.50,0.50,600,NaN,DEV
114,115,Junior Software Engineer,Python,NaN,1.5,0.5,685,250,Киев,до 1000 человек,...,False,средний,Другое,12/06/2017 13:14:52,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.50,0.50,685,NaN,DEV
143,144,Junior Software Engineer,Python,NaN,1,1,750,250,Киев,до 10 человек,...,True,выше среднего,Веб-разработка,12/06/2017 13:19:10,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.00,1.00,750,NaN,DEV
153,154,Software Engineer,Python,NaN,2,1,1200,0,Днепр,до 50 человек,...,False,продвинутый,"Веб-разработка,Мультимедиа",12/06/2017 13:20:15,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,2.00,1.00,1200,NaN,DEV
162,163,Junior Software Engineer,Python,NaN,0.5,0.5,500,0,Винница,до 200 человек,...,True,ниже среднего,Веб-разработка,12/06/2017 13:21:08,Mozilla/5.0 (Linux; Android 7.1.2; LG-D802 Bui...,0.50,0.50,500,NaN,DEV
171,172,Junior Software Engineer,Python,NaN,0.25,0.25,800,0,Киев,до 50 человек,...,False,продвинутый,Телекоммуникации,12/06/2017 13:22:31,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.25,0.25,800,NaN,DEV
217,218,Software Engineer,Python,NaN,8,2,2900,150,Львов,до 1000 человек,...,False,выше среднего,"Веб-разработка,Корпоративные системы",12/06/2017 13:31:50,Mozilla/5.0 (Windows NT 6.2; Win64; x64) Apple...,8.00,2.00,2900,NaN,DEV
302,303,Senior Software Engineer,Python,NaN,10 и более лет,0.5,3500,-300,Киев,до 200 человек,...,False,выше среднего,"Веб-разработка,Gamedev",12/06/2017 13:46:24,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,10.00,0.50,3500,NaN,DEV
373,374,Senior Software Engineer,Python,NaN,7,0.5,3100,1000,Днепр,до 200 человек,...,False,выше среднего,"Веб-разработка,Корпоративные системы",12/06/2017 13:58:16,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6...,7.00,0.50,3100,NaN,DEV
387,388,Software Engineer,Python,NaN,4,1.5,1200,0,Другой,до 10 человек,...,False,ниже среднего,"Веб-разработка,eCommerce",12/06/2017 14:01:02,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,4.00,1.50,1200,NaN,DEV
1172,1173,Senior Software Engineer,Python,NaN,2,2,1300,800,Львов,до 50 человек,...,True,средний,"Веб-разработка,Другое",12/06/2017 17:38:00,Mozilla/5.0 (Linux; Android 6.0.1; Redmi 3S Bu...,2.00,2.00,1300,NaN,DEV
1363,1364,Senior Software Engineer,Python,NaN,10 и более лет,2,1500,1000,Удаленно,до 10 человек,...,False,элементарный,"Системное программирование,Корпоративные системы",12/06/2017 19:10:01,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) ...,10.00,2.00,1500,NaN,DEV
1489,1490,Senior Software Engineer,Python,NaN,4,1,3300,430,Львов,до 1000 человек,...,False,выше среднего,"Веб-разработка,Корпоративные системы",12/06/2017 20:48:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.00,1.00,3300,NaN,DEV
2632,2633,Technical Lead,Python,NaN,4,1.5,3500,1000,Киев,до 50 человек,...,False,выше среднего,Веб-разработка,13/06/2017 12:37:02,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,4.00,1.50,3500,NaN,SDEV
3145,3146,Technical Lead,Python,NaN,10 и более лет,2,1425,475,Киев,до 50 человек,...,False,выше среднего,Корпоративные системы,13/06/2017 14:51:19,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52....,10.00,2.00,1425,NaN,SDEV
3935,3936,Technical Lead,Python,NaN,10 и более лет,0.25,3700,0,Киев,свыше 1000 человек,...,False,выше среднего,"Embedded,Другое",14/06/2017 12:26:36,Mozilla/5.0 (Linux; Android 5.0; SM-N900V Buil...,10.00,0.25,3700,NaN,SDEV
4323,4324,Technical Lead,Python,NaN,2,2,3300,800,Харьков,до 200 человек,...,False,средний,Веб-разработка,15/06/2017 11:16:57,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,2.00,2.00,3300,NaN,SDEV
4746,4747,Technical Lead,Python,NaN,5,3,2900,180,Днепр,до 10 человек,...,False,выше среднего,Веб-разработка,16/06/2017 21:46:04,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,5.00,3.00,2900,NaN,SDEV
5748,5749,System Architect,Python,NaN,10 и более лет,0.25,3000,0,Киев,до 50 человек,...,False,выше среднего,"Веб-разработка,eCommerce",20/06/2017 18:40:40,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,10.00,0.25,3000,NaN,SDEV
8228,8229,System Architect,Python,NaN,10 и более лет,2,5000,0,Киев,до 10 человек,...,False,средний,"Веб-разработка,Другое",06/07/2017 19:15:05,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4...,10.00,2.00,5000,NaN,SDEV

**Створіть новий DataFrame, де для згрупованих даних за стовпчиком "Посада", виконайте агрегацію даних за допомогою методу agg і знайдіть мінімальне та максимальне значення у стовпчику "Зарплата.в.місяць"**

In [68]:
range_salary = position.agg({'Зарплата.в.месяц':['min', 'max']})
range_salary

                         Зарплата.в.месяц
                                      min   max
Должность
Junior Software Engineer              100  1250
Senior Software Engineer             1300  9200
Software Engineer                     500  5400
System Architect                     3000  5000
Technical Lead                       1425  6200

**Створіть функцію fill_avg_salary, яка повертатиме середнє значення заробітної плати на місяць. Використовуйте її для методу apply та створіть новий стовпчик "avg"**

In [70]:
def fill_avg_salary(x):
    return x.mean()

In [72]:
range_salary['mean'] = range_salary.apply(fill_avg_salary, axis=1)
range_salary

                         Зарплата.в.месяц          mean
                                      min   max
Должность
Junior Software Engineer              100  1250   675.0
Senior Software Engineer             1300  9200  5250.0
Software Engineer                     500  5400  2950.0
System Architect                     3000  5000  4000.0
Technical Lead                       1425  6200  3812.5

**Створіть описову статистику за допомогою методу describe для нового стовпчи**

In [73]:
range_salary['mean'].describe()

count       5.000000
mean     3337.500000
std      1700.091909
min       675.000000
25%      2950.000000
50%      3812.500000
75%      4000.000000
max      5250.000000
Name: mean, dtype: float64

**Збережіть отриману таблицю в CSV файл**

In [74]:
range_salary.to_csv('Range_Salary.csv')